In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, \
roc_auc_score, roc_curve, confusion_matrix, cohen_kappa_score, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
import xgboost as xgb
import lightgbm as lgb
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import StackingClassifier

# Data Preprocessing

In [8]:
data = pd.read_csv('pd_speech_features.csv', skiprows=1)
data

id  gender      PPE      DFA     RPDE  numPulses  numPeriodsPulses  \
0      0       1  0.85247  0.71826  0.57227        240               239   
1      0       1  0.76686  0.69481  0.53966        234               233   
2      0       1  0.85083  0.67604  0.58982        232               231   
3      1       0  0.41121  0.79672  0.59257        178               177   
4      1       0  0.32790  0.79782  0.53028        236               235   
..   ...     ...      ...      ...      ...        ...               ...   
751  250       0  0.80903  0.56355  0.28385        417               416   
752  250       0  0.16084  0.56499  0.59194        415               413   
753  251       0  0.88389  0.72335  0.46815        381               380   
754  251       0  0.83782  0.74890  0.49823        340               339   
755  251       0  0.81304  0.76471  0.46374        340               339   

     meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...  \
0            0.008064            0.000087       0.00218  ...   
1            0.008258            0.000073       0.00195  ...   
2            0.008340            0.000060       0.00176  ...   
3            0.010858            0.000183       0.00419  ...   
4            0.008162            0.002669       0.00535  ...   
..                ...                 ...           ...  ...   
751          0.004627            0.000052       0.00064  ...   
752          0.004550            0.000220       0.00143  ...   
753          0.005069            0.000103       0.00076  ...   
754          0.005679            0.000055       0.00092  ...   
755          0.005676            0.000037       0.00078  ...   

     tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
0                       1.5620                     2.6445   
1                       1.5589                     3.6107   
2                       1.5643                     2.3308   
3                       3.7805                     3.5664   
4                       6.1727                     5.8416   
..                         ...                        ...   
751                     3.0706                     3.0190   
752                     1.9704                     1.7451   
753                    51.5607                    44.4641   
754                    19.1607                    12.8312   
755                    62.9927                    21.8152   

     tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
0                       3.8686                     4.2105   
1                      23.5155                    14.1962   
2                       9.4959                    10.7458   
3                       5.2558                    14.0403   
4                       6.0805                     5.7621   
..                         ...                        ...   
751                     3.1212                     2.4921   
752                     1.8277                     2.4976   
753                    26.1586                     6.3076   
754                     8.9434                     2.2044   
755                     9.2457                     4.8555   

     tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
0                       5.1221                     4.4625   
1                      11.0261                     9.5082   
2                      11.0177                     4.8066   
3                       4.2235                     4.6857   
4                       7.7817                    11.6891   
..                         ...                        ...   
751                     3.5844                     3.5400   
752                     5.2981                     4.2616   
753                     2.8601                     2.5361   
754                     1.9496                     1.9664   
755                     3.0551                     3.0415   

     tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
0                       2.6202                     3.0004   
1  

In [16]:
unique_ids = data['id'].unique()
train_ids, test_ids = train_test_split(unique_ids, test_size=0.3, random_state=19260817)

In [22]:
data[data['id'].isin(train_ids)]

id  gender      PPE      DFA     RPDE  numPulses  numPeriodsPulses  \
3      1       0  0.41121  0.79672  0.59257        178               177   
4      1       0  0.32790  0.79782  0.53028        236               235   
5      1       0  0.50780  0.78744  0.65451        226               221   
6      2       1  0.76095  0.62145  0.54543        322               321   
7      2       1  0.83671  0.62079  0.51179        318               317   
..   ...     ...      ...      ...      ...        ...               ...   
748  249       1  0.79645  0.78772  0.36342        340               339   
749  249       1  0.81171  0.79637  0.32824        336               335   
753  251       0  0.88389  0.72335  0.46815        381               380   
754  251       0  0.83782  0.74890  0.49823        340               339   
755  251       0  0.81304  0.76471  0.46374        340               339   

     meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...  \
3            0.010858            0.000183       0.00419  ...   
4            0.008162            0.002669       0.00535  ...   
5            0.007631            0.002696       0.00783  ...   
6            0.005991            0.000107       0.00222  ...   
7            0.006074            0.000136       0.00282  ...   
..                ...                 ...           ...  ...   
748          0.005686            0.000050       0.00084  ...   
749          0.005739            0.000041       0.00079  ...   
753          0.005069            0.000103       0.00076  ...   
754          0.005679            0.000055       0.00092  ...   
755          0.005676            0.000037       0.00078  ...   

     tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
3                       3.7805                     3.5664   
4                       6.1727                     5.8416   
5                       4.8025                     5.0734   
6                     117.2678                    75.3156   
7                       3.8564                    11.8909   
..                         ...                        ...   
748                    81.7657                    46.9118   
749                    71.9877                    52.2558   
753                    51.5607                    44.4641   
754                    19.1607                    12.8312   
755                    62.9927                    21.8152   

     tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
3                       5.2558                    14.0403   
4                       6.0805                     5.7621   
5                       7.0166                     5.9966   
6                      32.0478                     7.7060   
7                       7.2891                     4.3682   
..                         ...                        ...   
748                     8.7211                     3.8029   
749                    26.1383                     8.8848   
753                    26.1586                     6.3076   
754                     8.9434                     2.2044   
755                     9.2457                     4.8555   

     tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
3                       4.2235                     4.6857   
4                       7.7817                    11.6891   
5                       5.2065                     7.4246   
6                       3.1060                     4.6206   
7                       3.6443                     5.9610   
..                         ...                        ...   
748                     3.5360                     3.9038   
749                     7.5768                    18.2321   
753                     2.8601                     2.5361   
754                     1.9496                     1.9664   
755                     3.0551                     3.0415   

     tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
3                       4.8460                     6.2650   
4  

In [36]:
train_data = data[data['id'].isin(train_ids)].groupby('id').mean().reset_index().drop(columns=['id'])
test_data = data[data['id'].isin(test_ids)].groupby('id').mean().reset_index().drop(columns=['id'])
X_train, y_train = train_data.iloc[:,:-1], train_data.iloc[:,-1]
X_test, y_test = test_data.iloc[:,:-1], test_data.iloc[:,-1]

In [42]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train, X_test = X_train_scaled, X_test_scaled

# Model

In [50]:
def print_grid_search(gs):
    print ("Best score: " + str(gs.best_score_))
    print ("Best parameters set:")
    best_parameters = gs.best_params_
    for param_name in sorted(best_parameters.keys()):
        print(param_name + ':' + str(best_parameters[param_name]))

def get_metrics(model, mode = 'test'):
    if mode == 'train':
        X, y = X_train, y_train
    elif mode == 'test':
        X, y = X_test, y_test
    results = {}
    y_pred = model.predict(X)
    y_pred_prob = model.predict_proba(X)[:, 1]
    results['Accuracy'] = accuracy_score(y, y_pred)
    results['Precision'] = precision_score(y, y_pred)
    results['Recall'] = recall_score(y, y_pred)
    results['F1'] = f1_score(y, y_pred)
    # results['kappa'] = cohen_kappa_score(y, y_pred)
    results['AUC'] = roc_auc_score(y, y_pred_prob)
    return results

# def get_metrics_new(model, mode = 'test'):
#     if mode == 'train':
#         X, y = X_train_new, y_train
#     elif mode == 'test':
#         X, y = X_test_new, y_test
#     results = {}
#     y_pred = model.predict(X)
#     y_pred_prob = model.predict_proba(X)[:, 1]
#     results['accuracy'] = accuracy_score(y, y_pred)
#     results['precision'] = precision_score(y, y_pred)
#     results['recall'] = recall_score(y, y_pred)
#     results['f1'] = f1_score(y, y_pred)
#     # results['kappa'] = cohen_kappa_score(y, y_pred)
#     results['auc'] = roc_auc_score(y, y_pred_prob)
#     return results

def get_results(model):
    res1, res2 = get_metrics(model, mode='train'), get_metrics(model, mode='test')
    print(f'Train:\n{res1}')
    print(f'Test:\n{res2}')
    return res1, res2

# def get_results_new(model):
#     res1, res2 = get_metrics_new(model, mode='train'), get_metrics_new(model, mode='test')
#     print(f'Train:\n{res1}')
#     print(f'Test:\n{res2}')
#     return res1, res2

def get_coma(model):
    X, y = X_test, y_test
    y_pred = model.predict(X)
    return confusion_matrix(y, y_pred)

## Logistic Regression

In [53]:
params = {
    'C': [0.01, 0.1, 1.0],
    'penalty': ['l1', 'l2']
}
grid_lr = GridSearchCV(LogisticRegression(solver='liblinear',random_state=42), params)
grid_lr.fit(X_train, y_train)

GridSearchCV(estimator=LogisticRegression(random_state=42, solver='liblinear'),
             param_grid={'C': [0.01, 0.1, 1.0], 'penalty': ['l1', 'l2']})

In [55]:
print_grid_search(grid_lr)

Best score: 0.8071428571428572
Best parameters set:
C:0.1
penalty:l1


In [57]:
best_lr = grid_lr.best_estimator_
res_lr_train, res_lr_test = get_results(best_lr)

Train:
{'Accuracy': 0.875, 'Precision': 0.8657718120805369, 'Recall': 0.9847328244274809, 'F1': 0.9214285714285714, 'AUC': 0.9318066157760814}
Test:
{'Accuracy': 0.8552631578947368, 'Precision': 0.8382352941176471, 'Recall': 1.0, 'F1': 0.912, 'AUC': 0.863342566943675}


In [59]:
df_train_result = pd.DataFrame(res_lr_train, index=['Logistic Regression'])
df_test_result = pd.DataFrame(res_lr_test, index=['Logistic Regression'])

In [61]:
get_coma(best_lr)

array([[ 8, 11],
       [ 0, 57]], dtype=int64)

## Decision Tree

In [64]:
params = {
    'criterion': ['gini', 'entropy'],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
grid_dt = GridSearchCV(DecisionTreeClassifier(random_state=42), params, cv=5)
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

In [66]:
print_grid_search(grid_dt)

Best score: 0.6987301587301588
Best parameters set:
criterion:entropy
min_samples_leaf:4
min_samples_split:2


In [68]:
best_dt = grid_dt.best_estimator_
res_dt_train, res_dt_test = get_results(best_dt)

Train:
{'Accuracy': 0.9829545454545454, 'Precision': 0.9848484848484849, 'Recall': 0.9923664122137404, 'F1': 0.9885931558935361, 'AUC': 0.9983036471586089}
Test:
{'Accuracy': 0.6710526315789473, 'Precision': 0.7666666666666667, 'Recall': 0.8070175438596491, 'F1': 0.7863247863247863, 'AUC': 0.5932594644506002}


In [70]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_dt_train, index=['Decision Tree'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_dt_test, index=['Decision Tree'])], axis=0)

In [72]:
get_coma(best_dt)

array([[ 5, 14],
       [11, 46]], dtype=int64)

## Random Forest

In [75]:
params = {
    'n_estimators': [100, 200, 300],
    'max_features': ['log2', 'sqrt', 1]
}
grid_rf = GridSearchCV(RandomForestClassifier(random_state=42), params, cv=5)
grid_rf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_features': ['log2', 'sqrt', 1],
                         'n_estimators': [100, 200, 300]})

In [77]:
print_grid_search(grid_rf)

Best score: 0.8125396825396825
Best parameters set:
max_features:log2
n_estimators:300


In [79]:
best_rf = grid_rf.best_estimator_
res_rf_train, res_rf_test = get_results(best_rf)

Train:
{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1': 1.0, 'AUC': 1.0}
Test:
{'Accuracy': 0.8552631578947368, 'Precision': 0.8382352941176471, 'Recall': 1.0, 'F1': 0.912, 'AUC': 0.8536472760849492}


In [81]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_rf_train, index=['Random Forest'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_rf_test, index=['Random Forest'])], axis=0)

In [83]:
get_coma(best_rf)

array([[ 8, 11],
       [ 0, 57]], dtype=int64)

## Gradient Boosting

In [87]:
params = {
    'n_estimators': [800],
    'learning_rate': [0.01, 0.02],
    'max_depth': [3, 5],
    'max_features': ['sqrt', 'log2']
}
grid_gb = GridSearchCV(GradientBoostingClassifier(random_state=42), params, cv=5)
grid_gb.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(random_state=42),
             param_grid={'learning_rate': [0.01, 0.02], 'max_depth': [3, 5],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [800]})

In [91]:
print_grid_search(grid_gb)

Best score: 0.8125396825396825
Best parameters set:
learning_rate:0.02
max_depth:5
max_features:log2
n_estimators:800


In [93]:
best_gb = grid_gb.best_estimator_
res_gb_train, res_gb_test = get_results(best_gb)

Train:
{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1': 1.0, 'AUC': 1.0}
Test:
{'Accuracy': 0.8552631578947368, 'Precision': 0.8382352941176471, 'Recall': 1.0, 'F1': 0.912, 'AUC': 0.8716528162511542}


In [95]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_gb_train, index=['GBDT'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_gb_test, index=['GBDT'])], axis=0)

In [97]:
get_coma(best_gb)

array([[ 8, 11],
       [ 0, 57]], dtype=int64)

## XGBoost

In [101]:
params = {
    'n_estimators': [1000],
    'learning_rate': [0.01],
    'max_depth': [3],
    'min_child_weight': [1],
    'gamma': [0, 0.1],
    'subsample': [0.9],
    'colsample_bytree': [0.3],
}
grid_xgb = GridSearchCV(xgb.XGBClassifier(random_state=42), params, cv=5)
grid_xgb.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=42, ...),
             param_grid={'colsample_bytree': [0.3], 'gamma': [0, 0.1],
                         'learning_rate': [0.01], 'max_depth': [3],
                         'min_child_weight': [1], 'n_estimators': [1000],
                         'subsample': [0.9]})

In [103]:
print_grid_search(grid_xgb)

Best score: 0.7673015873015874
Best parameters set:
colsample_bytree:0.3
gamma:0
learning_rate:0.01
max_depth:3
min_child_weight:1
n_estimators:1000
subsample:0.9


In [105]:
best_xgb = grid_xgb.best_estimator_
res_xgb_train, res_xgb_test = get_results(best_xgb)

Train:
{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1': 1.0, 'AUC': 1.0}
Test:
{'Accuracy': 0.8552631578947368, 'Precision': 0.8382352941176471, 'Recall': 1.0, 'F1': 0.912, 'AUC': 0.8855032317636196}


In [107]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_xgb_train, index=['XGBoost'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_xgb_test, index=['XGBoost'])], axis=0)

In [109]:
get_coma(best_xgb)

array([[ 8, 11],
       [ 0, 57]], dtype=int64)

## LightGBM

In [112]:
params = {
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.2, 0.3, 0.4],
    'max_depth': [3],
    'num_leaves': [10],
    'subsample': [0.3, 0.5],
    'colsample_bytree': [0.7, 0.8, 0.9]
}
grid_lgb = GridSearchCV(lgb.LGBMClassifier(n_jobs=-1, verbose=-1), params, cv=5)
grid_lgb.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LGBMClassifier(n_jobs=-1, verbose=-1),
             param_grid={'colsample_bytree': [0.7, 0.8, 0.9],
                         'learning_rate': [0.2, 0.3, 0.4], 'max_depth': [3],
                         'n_estimators': [50, 100, 150], 'num_leaves': [10],
                         'subsample': [0.3, 0.5]})

In [114]:
print_grid_search(grid_lgb)

Best score: 0.8185714285714287
Best parameters set:
colsample_bytree:0.7
learning_rate:0.4
max_depth:3
n_estimators:50
num_leaves:10
subsample:0.3


In [116]:
best_lgb = grid_lgb.best_estimator_
res_lgb_train, res_lgb_test = get_results(best_lgb)

Train:
{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1': 1.0, 'AUC': 1.0}
Test:
{'Accuracy': 0.8289473684210527, 'Precision': 0.8333333333333334, 'Recall': 0.9649122807017544, 'F1': 0.8943089430894309, 'AUC': 0.8836565096952909}


In [118]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_lgb_train, index=['LightGBM'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_lgb_test, index=['LightGBM'])], axis=0)

In [120]:
get_coma(best_lgb)

array([[ 8, 11],
       [ 2, 55]], dtype=int64)

## KNN

In [128]:
params = {
    'n_neighbors': [3, 4, 5],
    'weights': ['uniform', 'distance'],
    'p': [1, 2]
}
grid_knn = GridSearchCV(KNeighborsClassifier(n_jobs=-1, algorithm='ball_tree'), params, cv=5)
grid_knn.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=KNeighborsClassifier(algorithm='ball_tree', n_jobs=-1),
             param_grid={'n_neighbors': [4, 5, 6, 7], 'p': [1, 2],
                         'weights': ['uniform', 'distance']})

In [130]:
print_grid_search(grid_knn)

Best score: 0.8125396825396827
Best parameters set:
n_neighbors:4
p:1
weights:distance


In [132]:
best_knn = grid_knn.best_estimator_
res_knn_train, res_knn_test = get_results(best_knn)

Train:
{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1': 1.0, 'AUC': 1.0}
Test:
{'Accuracy': 0.8421052631578947, 'Precision': 0.835820895522388, 'Recall': 0.9824561403508771, 'F1': 0.9032258064516129, 'AUC': 0.8351800554016621}


In [134]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_knn_train, index=['KNN'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_knn_test, index=['KNN'])], axis=0)

In [136]:
get_coma(best_knn)

array([[ 8, 11],
       [ 1, 56]], dtype=int64)

## SVM

In [139]:
params = {
    'C': [0.5, 1, 2],
    'gamma': ['scale', 'auto'],
}
grid_svm = GridSearchCV(SVC(random_state=42, probability=True), params, cv=5)
grid_svm.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(probability=True, random_state=42),
             param_grid={'C': [0.5, 1, 2], 'gamma': ['scale', 'auto']})

In [141]:
print_grid_search(grid_svm)

Best score: 0.8122222222222222
Best parameters set:
C:2
gamma:scale


In [143]:
best_svm = grid_svm.best_estimator_
res_svm_train, res_svm_test = get_results(best_svm)

Train:
{'Accuracy': 0.9772727272727273, 'Precision': 0.9703703703703703, 'Recall': 1.0, 'F1': 0.9849624060150376, 'AUC': 0.9998303647158608}
Test:
{'Accuracy': 0.8421052631578947, 'Precision': 0.835820895522388, 'Recall': 0.9824561403508771, 'F1': 0.9032258064516129, 'AUC': 0.7728531855955678}


In [146]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_svm_train, index=['SVM'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_svm_test, index=['SVM'])], axis=0)

In [148]:
get_coma(best_svm)

array([[ 8, 11],
       [ 1, 56]], dtype=int64)

## Naive Bayes

In [150]:
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [152]:
res_nb_train, res_nb_test = get_results(nb)

Train:
{'Accuracy': 0.8352272727272727, 'Precision': 0.9047619047619048, 'Recall': 0.8702290076335878, 'F1': 0.8871595330739299, 'AUC': 0.8425784563189143}
Test:
{'Accuracy': 0.7763157894736842, 'Precision': 0.8703703703703703, 'Recall': 0.8245614035087719, 'F1': 0.8468468468468469, 'AUC': 0.7922437673130194}


In [155]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_nb_train, index=['Naive Bayes'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_nb_test, index=['Naive Bayes'])], axis=0)

In [157]:
get_coma(best_svm)

array([[ 8, 11],
       [ 1, 56]], dtype=int64)

## AdaBoost

In [161]:
best_ada = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1), 
    n_estimators=100,
    learning_rate=0.5, 
    random_state=42
).fit(X_train, y_train)

D:\Users\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [163]:
res_ada_train, res_ada_test = get_results(best_ada)

Train:
{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1': 1.0, 'AUC': 1.0}
Test:
{'Accuracy': 0.8157894736842105, 'Precision': 0.8412698412698413, 'Recall': 0.9298245614035088, 'F1': 0.8833333333333333, 'AUC': 0.8531855955678669}


In [166]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_ada_train, index=['AdaBoost'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_ada_test, index=['AdaBoost'])], axis=0)

In [168]:
get_coma(best_ada)

array([[ 9, 10],
       [ 4, 53]], dtype=int64)

## MLP

In [171]:
mlp_model = MLPClassifier(random_state=42, hidden_layer_sizes=(512,256,128), learning_rate_init=0.001)
mlp_model.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(512, 256, 128), random_state=42)

In [173]:
res_mlp_train, res_mlp_test = get_results(mlp_model)

Train:
{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1': 1.0, 'AUC': 1.0}
Test:
{'Accuracy': 0.9078947368421053, 'Precision': 0.890625, 'Recall': 1.0, 'F1': 0.9421487603305785, 'AUC': 0.8347183748845798}


In [175]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_mlp_train, index=['MLP'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_mlp_test, index=['MLP'])], axis=0)

In [177]:
get_coma(mlp_model)

array([[12,  7],
       [ 0, 57]], dtype=int64)

## Stacking

In [186]:
estimators = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc', SVC(probability=True, gamma='auto', random_state=42))
]
final_estimator = LogisticRegression(solver='liblinear', random_state=42)

stacking_clf = StackingClassifier(estimators=estimators, final_estimator=final_estimator)

params = {
    'dt__min_samples_split': [2, 5],
    'svc__C': [0.1, 1, 10],
    'final_estimator__C': [1, 10],
    'final_estimator__penalty': ['l1', 'l2']
}
grid_stack = GridSearchCV(estimator=stacking_clf, param_grid=params, cv=5, n_jobs=-1)
grid_stack.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=StackingClassifier(estimators=[('dt',
                                                       DecisionTreeClassifier(random_state=42)),
                                                      ('svc',
                                                       SVC(gamma='auto',
                                                           probability=True,
                                                           random_state=42))],
                                          final_estimator=LogisticRegression(random_state=42,
                                                                             solver='liblinear')),
             n_jobs=-1,
             param_grid={'dt__min_samples_split': [2, 5],
                         'final_estimator__C': [1, 10],
                         'final_estimator__penalty': ['l1', 'l2'],
                         'svc__C': [0.1, 1, 10]})

In [188]:
print_grid_search(grid_stack)

Best score: 0.8236507936507937
Best parameters set:
dt__min_samples_split:5
final_estimator__C:1
final_estimator__penalty:l1
svc__C:10


In [190]:
best_stack = grid_stack.best_estimator_
res_stack_train, res_stack_test = get_results(best_stack)

Train:
{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1': 1.0, 'AUC': 1.0}
Test:
{'Accuracy': 0.8552631578947368, 'Precision': 0.8484848484848485, 'Recall': 0.9824561403508771, 'F1': 0.9105691056910569, 'AUC': 0.7922437673130194}


In [192]:
df_train_result = pd.concat([df_train_result, pd.DataFrame(res_stack_train, index=['Stacking'])], axis=0)
df_test_result = pd.concat([df_test_result, pd.DataFrame(res_stack_test, index=['Stacking'])], axis=0)

In [194]:
get_coma(best_stack)

array([[ 9, 10],
       [ 1, 56]], dtype=int64)

# Evaluation

In [197]:
df_test_result_sorted = df_test_result.sort_values(by='Accuracy', ascending=False)
df_train_result_reordered = df_train_result.reindex(df_test_result_sorted.index)
print('Train:')
df_train_result_reordered

Train:


Accuracy  Precision    Recall        F1       AUC
MLP                  1.000000   1.000000  1.000000  1.000000  1.000000
Logistic Regression  0.875000   0.865772  0.984733  0.921429  0.931807
Random Forest        1.000000   1.000000  1.000000  1.000000  1.000000
GBDT                 1.000000   1.000000  1.000000  1.000000  1.000000
XGBoost              1.000000   1.000000  1.000000  1.000000  1.000000
Stacking             1.000000   1.000000  1.000000  1.000000  1.000000
KNN                  1.000000   1.000000  1.000000  1.000000  1.000000
SVM                  0.977273   0.970370  1.000000  0.984962  0.999830
LightGBM             1.000000   1.000000  1.000000  1.000000  1.000000
AdaBoost             1.000000   1.000000  1.000000  1.000000  1.000000
Naive Bayes          0.835227   0.904762  0.870229  0.887160  0.842578
Decision Tree        0.982955   0.984848  0.992366  0.988593  0.998304

In [199]:
print('Test:')
df_test_result_sorted

Test:


Accuracy  Precision    Recall        F1       AUC
MLP                  0.907895   0.890625  1.000000  0.942149  0.834718
Logistic Regression  0.855263   0.838235  1.000000  0.912000  0.863343
Random Forest        0.855263   0.838235  1.000000  0.912000  0.853647
GBDT                 0.855263   0.838235  1.000000  0.912000  0.871653
XGBoost              0.855263   0.838235  1.000000  0.912000  0.885503
Stacking             0.855263   0.848485  0.982456  0.910569  0.792244
KNN                  0.842105   0.835821  0.982456  0.903226  0.835180
SVM                  0.842105   0.835821  0.982456  0.903226  0.772853
LightGBM             0.828947   0.833333  0.964912  0.894309  0.883657
AdaBoost             0.815789   0.841270  0.929825  0.883333  0.853186
Naive Bayes          0.776316   0.870370  0.824561  0.846847  0.792244
Decision Tree        0.671053   0.766667  0.807018  0.786325  0.593259